name: Checkmarx AST Scan

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  checkmarx-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Run Checkmarx AST Scan
        uses: checkmarx/ast-github-action@1fe318de2993222574e6249750ba9000a4e2a6cd

        with:
          base_uri: https://ind.ast.checkmarx.net/
          cx_tenant: cdac

          # Store these in GitHub Secrets
          cx_client_id: additinal_params
          cx_client_secret: ZzZOQEwkPdMdnZI9JHAwlfEoJgyV1McN

          # Project details
          project_name: github_repo

          # Scan parameters
          scan_params: >
            --scan-types sast
            --sast-preset-name "Checkmarx Default"
            --report-format json
            --output-path ./cx-results
            --threshold "sast-high=1;sast-medium=1"

      - name: Upload Scan Reports
        uses: actions/upload-artifact@v4
        with:
          name: checkmarx-reports
          path: ./cx-results
